[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/"
  status = 301

[[redirects]]
  from = "/RecepiesApp"
  to = "/RecepiesApp"
  status = 301

[[redirects]]
  from = "/TrainingApp"
  to = "/TrainingApp"
  status = 301

[[redirects]]
  from = "/BookingApp"
  to = "/BookingApp"
  status = 301
